package com.litert.tunnel.ui.strings

import androidx.compose.runtime.compositionLocalOf

enum class AppLanguage { EN, KO }

/**
 * All UI-visible strings. Dynamic strings (with parameters) are lambdas.
 * Use [LocalStrings] to read the current set inside any Composable.
 */
class AppStrings(
    // ── Navigation ────────────────────────────────────────────────────
    val tabServer: String,
    val tabChat: String,
    val tabModels: String,
    val tabMonitor: String,

    // ── ServerScreen ──────────────────────────────────────────────────
    val statusRunning: String,
    val statusLoading: String,
    val statusError: String,
    val statusStopped: String,
    val statusIdle: String,
    val startServer: String,
    val stopServer: String,
    val loadingBtn: String,
    val backendLabel: String,
    val recentRequests: String,
    val onDevice: String,
    val lan: String,
    val tapToCopy: String,
    val noLanAddress: String,
    val copied: String,
    val reqCount: (Long) -> String,

    // ── ChatScreen ────────────────────────────────────────────────────
    val chatTitle: String,
    val messagePlaceholder: String,
    val generating: String,
    val engineNotReady: String,

    // ── ModelsScreen ──────────────────────────────────────────────────
    val modelsTitle: String,
    val storedIn: String,
    val active: String,
    val use: String,
    val delete: String,
    val download: String,
    val downloading: String,
    val loadCustom: String,

    // ── MonitorScreen ─────────────────────────────────────────────────
    val monitorTitle: String,
    val kvCacheTitle: (max: Int) -> String,
    val turnLabel: (current: Int, max: Int) -> String,
    val autoResetBadge: (count: Int) -> String,
    val obsCardTitle: (count: Int) -> String,
    val latestCharsLabel: (chars: Int) -> String,
    val limitLabel: String,
    val oldest: String,
    val latestDot: String,
    val trim: String,
    val noDataYet: String,
    val statsTitle: String,
    val statCurrentTurn: String,
    val statMaxTurns: String,
    val statAutoResets: String,
    val statTurnsLogged: String,
    val statLastInput: String,
    val statAvgInput: String,
    val statPeakInput: String,
    val charsSuffix: String,
    val settingsTitle: String,
    val maxKvTurns: String,
    val kvTurnsDesc: (min: Int, max: Int) -> String,
    val contextReplay: String,
    val contextReplayDesc: (max: Int) -> String,
    val off: String,
    val maxObsChars: String,
    val obsCharsDesc: (min: Int, max: Int) -> String,
    val languageLabel: String,

    // ── CORS settings ─────────────────────────────────────────────────
    val corsTitle: String,
    val corsDesc: String,
    val corsAllowAll: String,
    val corsAddHint: String,
    val corsAdd: String,
    val corsEmpty: String,
)

val EnglishStrings = AppStrings(
    tabServer = "Server",
    tabChat = "Chat",
    tabModels = "Models",
    tabMonitor = "Monitor",

    statusRunning = "Running",
    statusLoading = "Loading",
    statusError = "Error",
    statusStopped = "Stopped",
    statusIdle = "Idle",
    startServer = "Start Server",
    stopServer = "Stop Server",
    loadingBtn = "Loading…",
    backendLabel = "Backend: ",
    recentRequests = "Recent requests",
    onDevice = "On-device (Termux)",
    lan = "LAN",
    tapToCopy = "Tap URL to copy",
    noLanAddress = "No LAN address found — check Wi-Fi connection",
    copied = "✓ Copied!",
    reqCount = { "$it req" },

    chatTitle = "Chat",
    messagePlaceholder = "Message…",
    generating = "Generating…",
    engineNotReady = "Engine not ready — start the server first.",

    modelsTitle = "Models",
    storedIn = "Stored in: ",
    active = "Active",
    use = "Use",
    delete = "Delete",
    download = "Download",
    downloading = "Downloading…",
    loadCustom = "Load custom .litertlm file…",

    monitorTitle = "Engine Monitor",
    kvCacheTitle = { "KV CACHE TURNS  (max $it)" },
    turnLabel = { c, m -> "Turn $c / $m" },
    autoResetBadge = { "⚡ ${it}× reset" },
    obsCardTitle = { "OBSERVATION SIZE  (last $it turns)" },
    latestCharsLabel = { "Latest: $it chars" },
    limitLabel = "limit",
    oldest = "oldest",
    latestDot = "latest ●",
    trim = "trim",
    noDataYet = "No data yet — start the server and send a message.",
    statsTitle = "STATS",
    statCurrentTurn = "Current turn",
    statMaxTurns = "Max turns (limit)",
    statAutoResets = "Auto-resets",
    statTurnsLogged = "Turns logged",
    statLastInput = "Last input",
    statAvgInput = "Avg input",
    statPeakInput = "Peak input",
    charsSuffix = " chars",
    settingsTitle = "SETTINGS  (apply instantly, persisted)",
    maxKvTurns = "Max KV cache turns",
    kvTurnsDesc = { min, max -> "Auto-reset threshold  ($min–$max)" },
    contextReplay = "Context replay turns",
    contextReplayDesc = { "Prior turns replayed after reset  (0 = hard reset, max $it)" },
    off = "off",
    maxObsChars = "Max observation chars",
    obsCharsDesc = { min, max -> "Server-side trim  ($min–$max)" },
    languageLabel = "Language",

    corsTitle = "CORS Allowed Origins",
    corsDesc = "Substring-matched against the Origin header. Use * to allow all.",
    corsAllowAll = "Allow all (*)",
    corsAddHint = "e.g. 10.0.0. or myhost",
    corsAdd = "Add",
    corsEmpty = "No origins allowed — all cross-origin requests will be blocked.",
)

val KoreanStrings = AppStrings(
    tabServer = "서버",
    tabChat = "채팅",
    tabModels = "모델",
    tabMonitor = "모니터",

    statusRunning = "실행 중",
    statusLoading = "로딩 중",
    statusError = "오류",
    statusStopped = "중지됨",
    statusIdle = "대기",
    startServer = "서버 시작",
    stopServer = "서버 중지",
    loadingBtn = "로딩 중…",
    backendLabel = "백엔드: ",
    recentRequests = "최근 요청",
    onDevice = "기기 내 (Termux)",
    lan = "LAN",
    tapToCopy = "URL 탭하면 복사",
    noLanAddress = "LAN 주소 없음 — Wi-Fi 연결을 확인하세요",
    copied = "✓ 복사됨!",
    reqCount = { "${it}건" },

    chatTitle = "채팅",
    messagePlaceholder = "메시지…",
    generating = "생성 중…",
    engineNotReady = "엔진 준비 안 됨 — 서버를 먼저 시작하세요.",

    modelsTitle = "모델",
    storedIn = "저장 위치: ",
    active = "활성",
    use = "사용",
    delete = "삭제",
    download = "다운로드",
    downloading = "다운로드 중…",
    loadCustom = "커스텀 .litertlm 파일 불러오기…",

    monitorTitle = "엔진 모니터",
    kvCacheTitle = { "KV 캐시 턴  (최대 $it)" },
    turnLabel = { c, m -> "$c / $m 턴" },
    autoResetBadge = { "⚡ ${it}× 리셋" },
    obsCardTitle = { "관측 크기  (최근 $it 턴)" },
    latestCharsLabel = { "최신: $it 문자" },
    limitLabel = "제한",
    oldest = "이전",
    latestDot = "최신 ●",
    trim = "트림",
    noDataYet = "데이터 없음 — 서버 시작 후 메시지를 보내세요.",
    statsTitle = "통계",
    statCurrentTurn = "현재 턴",
    statMaxTurns = "최대 턴 (제한)",
    statAutoResets = "자동 리셋",
    statTurnsLogged = "기록된 턴",
    statLastInput = "최근 입력",
    statAvgInput = "평균 입력",
    statPeakInput = "최대 입력",
    charsSuffix = " 문자",
    settingsTitle = "설정  (즉시 적용, 저장됨)",
    maxKvTurns = "최대 KV 캐시 턴",
    kvTurnsDesc = { min, max -> "자동 리셋 임계값  ($min–$max)" },
    contextReplay = "컨텍스트 리플레이 턴",
    contextReplayDesc = { "리셋 후 재생 턴 수  (0 = 하드 리셋, 최대 $it)" },
    off = "꺼짐",
    maxObsChars = "최대 관측 문자",
    obsCharsDesc = { min, max -> "서버 측 트림  ($min–$max)" },
    languageLabel = "언어",

    corsTitle = "CORS 허용 주소",
    corsDesc = "Origin 헤더에 포함된 문자열과 매칭됩니다. *로 설정하면 모두 허용.",
    corsAllowAll = "모두 허용 (*)",
    corsAddHint = "예) 10.0.0. 또는 myhost",
    corsAdd = "추가",
    corsEmpty = "허용된 주소 없음 — 모든 크로스 오리진 요청이 차단됩니다.",
)

fun appStringsFor(language: AppLanguage): AppStrings = when (language) {
    AppLanguage.EN -> EnglishStrings
    AppLanguage.KO -> KoreanStrings
}

val LocalStrings = compositionLocalOf<AppStrings> { EnglishStrings }
